export {
  adoptExternalSessionFromHook,
  ensureProjectScan,
  getDismissalTracker,
  isTrackedProjectDir,
  readNewLines,
  reassignAgentToFile,
  scanAllTeammateFiles,
  scanExternalDir,
  scanForNewJsonlFiles,
  scanForTeammateFiles,
  scanTeamConfigsForRemovals,
  setAgentRemovalCallback,
  setDismissalTracker,
  setHookProvider,
  setTeammateRemovalCallback,
  setTeamProvider,
  setTerminalAdapter,
  startExternalSessionScanning,
  startFileWatching,
  startStaleExternalAgentCheck,
} from './watcher/index.js';
